OUTPUT:
b'\r\nC:\\GitHub\\CWatM\\Tutorials\\09_Calibration_renovation\\runs_calibration\\00_008>python ../../../../run_cwatm.py settings_CWatM_template_30min-Run00_008.ini -v \r\n'
ERRORS:
b'Traceback (most recent call last):\r\n  File "C:\\GitHub\\CWatM\\run_cwatm.py", line 35, in <module>\r\n    from cwatm.run_cwatm import main, parse_args, usage, GNU\r\n  File "C:\\GitHub\\CWatM\\cwatm\\run_cwatm.py", line 46, in <module>\r\n    import pandas\r\n  File "C:\\Users\\smilovic\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\__init__.py", line 22, in <module>\r\n    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401\r\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\smilovic\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\compat\\__init__.py", line 18, in <module>\r\n    from pandas.compat.numpy import (\r\n  File "C:\\Users\\smilovic\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\compat\\numpy\\__init__.py", line 4, in <module>\r\n    from pandas.util.version import Version\r\n  File "C:\\Users\\smilovic\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\util\\__init__.py", line 2, in <module>\r\n    from pandas.util._decorators import (  # noqa:F401\r\n  File "C:\\Users\\smilovic\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\util\\_decorators.py", line 14, in <module>\r\n    from pandas._libs.properties import cache_readonly\r\n  File "C:\\Users\\smilovic\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\_libs\\__init__.py", line 13, in <module>\r\n    from pandas._libs.interval import Interval\r\n  File "pandas\\_libs\\interval.pyx", line 1, in init pandas._libs.interval\r\n  File "pandas\\_libs\\hashtable.pyx", line 1, in init pandas._libs.hashtable\r\n  File "pandas\\_libs\\missing.pyx", line 1, in init pandas._libs.missing\r\n  File "C:\\Users\\smilovic\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\_libs\\tslibs\\__init__.py", line 37, in <module>\r\n    from pandas._libs.tslibs.conversion import localize_pydatetime\r\n  File "pandas\\_libs\\tslibs\\conversion.pyx", line 1, in init pandas._libs.tslibs.conversion\r\nImportError: DLL load failed while importing nattype: The paging file is too small for this operation to complete.\r\n'